# Makefile generated by imake - do not edit!
# $XConsortium: imake.c,v 1.89 94/08/12 00:45:51 gildea Exp $

# -----------------------------------------------------------------------
# Makefile generated from "Imake.tmpl" and <Imakefile>
# $XConsortium: Imake.tmpl,v 1.219 94/05/13 15:58:31 matt Exp $
# $SunSoft: @(#)Imake.tmpl	1.1 01/13/97 16:16:22 $
#

# **************************************************************************
# NOTE:
#
# If the user does not define DESTDIR and/or BINDIR in the local Imakefile,
# 'make install' will install the resultant binaries in /usr/openwin/bin.
# This usually fails because of lack of write permission in that directory
# for non-root users.
#
# The reason is that the default definition of ProjectRoot is /usr/openwin.
# This value determines all other definitions, e.g. the binary, library and
# manual page directories, etc.  The destination directory, DESTDIR, is not
# defined and BINDIR is defined as $(ProjectRoot)/bin in Project.tmpl.
#
# Care must be taken when changing ProjectRoot.  It affects the inclusion
# path of 'imake' in finding the *.cf, *.def, *.tmpl and *.rules files,
# which are in /usr/openwin/lib/X11/config/, and the default inclusion path
# of X11 header files and libraries. Therefore, if ProjectRoot is changed
# not only these configuration files need to be copied to a proper location,
# defined by IRULESRC, so 'make Makefile' can work properly, the header file
# inclusion path, /usr/openwin/include, and the library search path,
# /usr/openwin/lib, also need to be defined properly either in the local
# Imakefile or one of the configuration files to avoid compilation errors
# for programs that use X11 header files or libraries.
#
# Please refer to Project.tmpl, Imake.tmpl, site.def, etc. in
# /usr/openwin/lib/X11/config/ for details.
# **************************************************************************

.SUFFIXES: .i

# $XConsortium: Imake.cf,v 1.12 94/03/29 15:42:08 gildea Exp $
# $SunSoft: @(#)Imake.cf	1.1 01/13/97 16:16:21 $

# -----------------------------------------------------------------------
# site-specific configuration parameters that need to come before
# the platform-specific parameters - edit site.def to change

# site:  $XConsortium: site.sample,v 1.11 94/06/03 19:50:12 matt Exp $
# site:  $SunSoft: @(#)site.def	1.1 01/13/97 16:16:27$

# -----------------------------------------------------------------------
# platform-specific configuration parameters - edit sun.cf to change

# platform:  $XConsortium: sun.cf,v 1.133 94/07/08 12:23:12 gildea Exp $
# platform:  $SunSoft: @(#)sun.cf	1.12 03/12/02 15:19:08 $

# operating system:  SunOS 5.10 x86

# SUNSOFT SUNSOFT_LOADABLE

# $XConsortium: svr4.cf,v 1.6 94/04/08 18:56:33 rws Exp $
# $SunSoft: @(#)svr4.cf	1.1 01/13/97 16:16:29 $

# $XConsortium: sv4Lib.rules,v 1.14 94/04/09 12:00:10 rws Exp $
# $SunSoft: @(#)sv4Lib.rules	1.1 01/13/97 16:16:28 $

# SUNSOFT SUNSOFT_LOADABLE

	TROFFTOPS = /usr/lib/lp/postscript/dpost | /usr/lib/lp/postscript/postreverse -r

# -----------------------------------------------------------------------
# site-specific configuration parameters that go after
# the platform-specific parameters - edit site.def to change

# site:  $XConsortium: site.sample,v 1.11 94/06/03 19:50:12 matt Exp $
# site:  $SunSoft: @(#)site.def	1.1 01/13/97 16:16:27$

# -----------------------------------------------------------------------
# Imake rules for building libraries, programs, scripts, and data files
# rules:  $XConsortium: Imake.rules,v 1.193 94/04/10 17:39:55 rws Exp $
# rules:  $SunSoft: @(#)Imake.rules	1.1 01/13/97 16:16:21 $

# SUNSOFT SUNSOFT_LOADABLE

          PATHSEP = /
            SHELL = /bin/sh

              TOP = .
      CURRENT_DIR = .

            IMAKE = imake
           DEPEND = makedepend
        MKDIRHIER = mkdirhier
        CONFIGSRC = $(TOP)/config
         IMAKESRC = $(CONFIGSRC)/imake
        DEPENDSRC = $(CONFIGSRC)/makedepend
           IXXSRC = $(UNSUPPORTEDSRC)/programs/ixx
              IXX = ixx
         IXXFLAGS = -s BaseObject -m TypeObj -r RequestObj -p Xf
      IXXINCLUDES = -i '<X11/Fresco/enter-scope.h>'

          INCROOT = /usr/openwin/include
        USRLIBDIR = /usr/openwin/lib
         SHLIBDIR = /usr/openwin/lib
       LINTLIBDIR = $(USRLIBDIR)
          MANPATH = /usr/openwin/share/man
    MANSOURCEPATH = $(MANPATH)/man
           MANDIR = $(MANSOURCEPATH)1
        LIBMANDIR = $(MANSOURCEPATH)3
       FILEMANDIR = $(MANSOURCEPATH)$(FILEMANSUFFIX)

               AR = /usr/ccs/bin/ar cq
  BOOTSTRAPCFLAGS = -DSVR4
               CC = cc
               AS = /usr/ccs/bin/as

         COMPRESS = compress
              CPP = /usr/ccs/lib/cpp $(STD_CPP_DEFINES)
    PREPROCESSCMD = cc -E $(STD_CPP_DEFINES)
          INSTALL = /usr/ucb/install
     INSTALLFLAGS = -c
               LD = /usr/ccs/bin/ld
              LEX = /usr/ccs/bin/lex
           LEXLIB = -ll
             YACC = /usr/ccs/bin/yacc
           CCYACC = /usr/ccs/bin/yacc
             LINT = lint
      LINTLIBFLAG = -y -o
         LINTOPTS = -b -h -Xc
               LN = ln -s
             MAKE = /usr/ccs/bin/make
               MV = mv
               CP = cp

               RM = rm -f
        MANSUFFIX = 1
     LIBMANSUFFIX = 3
    FILEMANSUFFIX = 4
            TROFF = troff -t -Tpost
         MSMACROS = -ms
              TBL = tbl
              EQN = eqn

            DVIPS = dvips
            LATEX = latex

     STD_INCLUDES =
  STD_CPP_DEFINES = -Dsun -Di386 -DSVR4 -DSYSV
      STD_DEFINES = -Dsun -Di386 -DSVR4 -DSYSV
 EXTRA_LOAD_FLAGS =
  EXTRA_LDOPTIONS =
  EXTRA_LIBRARIES = -lsocket -lnsl
             TAGS = ctags

    SHAREDCODEDEF =
         SHLIBDEF =

     SHLIBLDFLAGS = -G -z text -M mapfile

         PICFLAGS = -Kpic

      CXXPICFLAGS = -K PIC

    PROTO_DEFINES =

     INSTPGMFLAGS =

     INSTBINFLAGS = -m 0755
     INSTUIDFLAGS = -m 4755
     INSTLIBFLAGS = -m 0644
     INSTINCFLAGS = -m 0644
     INSTMANFLAGS = -m 0444
     INSTDATFLAGS = -m 0444
    INSTKMEMFLAGS = -g sys -m 2755

      PROJECTROOT = /usr/openwin

     TOP_INCLUDES = -I$(INCROOT)

      CDEBUGFLAGS = -O
        CCOPTIONS = -Xc -Dasm=__asm

      ALLINCLUDES = $(INCLUDES) $(EXTRA_INCLUDES) $(TOP_INCLUDES) $(STD_INCLUDES)
       ALLDEFINES = $(ALLINCLUDES) $(STD_DEFINES) $(EXTRA_DEFINES) $(PROTO_DEFINES) $(THREADS_DEFINES) $(DEFINES)
           CFLAGS = $(CDEBUGFLAGS) $(CCOPTIONS) $(THREADS_CFLAGS) $(ALLDEFINES)
        LINTFLAGS = $(LINTOPTS) -DLINT $(ALLDEFINES) $(DEPEND_DEFINES)
         LDPRELIB = -L$(USRLIBDIR)
        LDPOSTLIB =
        LDOPTIONS = $(CDEBUGFLAGS) $(CCOPTIONS)  $(EXTRA_LDOPTIONS) $(THREADS_LDFLAGS) $(LOCAL_LDFLAGS) $(LDPRELIB)
     CXXLDOPTIONS = $(CXXDEBUGFLAGS) $(CXXOPTIONS) $(EXTRA_LDOPTIONS) $(THREADS_CXXLDFLAGS) $(LOCAL_LDFLAGS) $(LDPRELIB)

           LDLIBS = $(LDPOSTLIB) $(THREADS_LIBS) $(SYS_LIBRARIES) $(EXTRA_LIBRARIES)

       CCENVSETUP = LD_RUN_PATH=$(USRLIBDIR)
           CCLINK = $(CCENVSETUP) $(CC)

      CXXENVSETUP = LD_RUN_PATH=$(USRLIBDIR)
          CXXLINK = $(CXXENVSETUP) $(CXX)

     LDSTRIPFLAGS = -x
   LDCOMBINEFLAGS = -r
      DEPENDFLAGS =

        MACROFILE = sun.cf
           RM_CMD = $(RM)

    IMAKE_DEFINES =

         IRULESRC = $(CONFIGDIR)
        IMAKE_CMD = $(IMAKE) -DUseInstalled -I$(IRULESRC) $(IMAKE_DEFINES)

     ICONFIGFILES = $(IRULESRC)/Imake.tmpl $(IRULESRC)/Project.tmpl \
			$(IRULESRC)/site.def $(IRULESRC)/$(MACROFILE) \
			 $(EXTRA_ICONFIGFILES)

# -----------------------------------------------------------------------
# X Window System Build Parameters and Rules
# $XConsortium: Project.tmpl,v 1.242 94/04/13 14:58:40 rws Exp $
# $SunSoft: @(#)Project.tmpl	1.6 05/30/02 19:12:02 $

# SUNSOFT SUNSOFT_LOADABLE

# -----------------------------------------------------------------------
# X Window System make variables; these need to be coordinated with rules

           BINDIR = /usr/openwin/bin
     BUILDINCROOT = $(TOP)
      BUILDINCDIR = $(BUILDINCROOT)/X11
      BUILDINCTOP = ..
      BUILDLIBDIR = $(TOP)/usrlib
      BUILDLIBTOP = ..
           INCDIR = $(INCROOT)/X11
           ADMDIR = /usr/adm
           LIBDIR = $(USRLIBDIR)/X11

          FONTDIR = $(LIBDIR)/fonts
         XINITDIR = $(LIBDIR)/xinit
           XDMDIR = $(LIBDIR)/xdm
           TWMDIR = $(LIBDIR)/twm
           NLSDIR = $(LIBDIR)/nls
       XLOCALEDIR = $(PROJECTROOT)/lib/locale
        PEXAPIDIR = $(LIBDIR)/PEX
      XAPPLOADDIR = $(LIBDIR)/app-defaults
       FONTCFLAGS = -t

     INSTAPPFLAGS = $(INSTDATFLAGS)

              RGB = rgb
            FONTC = bdftopcf
        MKFONTDIR = mkfontdir

       DOCUTILSRC = $(TOP)/doc/util
       XDOCMACROS = $(DOCUTILSRC)/macros.t
       XIDXMACROS = $(DOCUTILSRC)/indexmacros.t
       PROGRAMSRC = $(TOP)/programs
           LIBSRC = $(TOP)/lib
          FONTSRC = $(TOP)/fonts
       INCLUDESRC = $(TOP)/X11
        SERVERSRC = $(TOP)/programs/Xserver
       CONTRIBSRC = $(TOP)/../contrib
   UNSUPPORTEDSRC = $(TOP)/unsupported
           DOCSRC = $(TOP)/doc
           RGBSRC = $(TOP)/programs/rgb
      BDFTOPCFSRC = $(PROGRAMSRC)/bdftopcf
     MKFONTDIRSRC = $(PROGRAMSRC)/mkfontdir
    FONTSERVERSRC = $(PROGRAMSRC)/xfs
       FONTINCSRC = $(TOP)/include/fonts
        EXTINCSRC = $(TOP)/include/extensions
     TRANSCOMMSRC = $(LIBSRC)/xtrans
   TRANS_INCLUDES = -I$(TRANSCOMMSRC)

# $XConsortium: sunLib.tmpl,v 1.37 95/05/23 14:31:40 matt Exp $
# SunSoft: @(#)sunLib.tmpl	1.4 05/30/02 17:00:20

# $XConsortium: sv4Lib.tmpl,v 1.19 93/12/03 10:48:36 kaleb Exp $
# $SunSoft: @(#)sv4Lib.tmpl	1.1 01/13/97 16:16:29 $

XMULIBONLY = -lXmu -lm
XMULIB = -lXmu -lm

       SERVERLIB = /usr/openwin/server/lib

	SERVERMODULES = /usr/openwin/server/modules

	SERVERETC = /usr/openwin/server/etc

SHLIBLDFLAGS = -G -z text -M mapfile
PICFLAGS = -Kpic
MAPFILE = mapfile

          XLIBSRC = $(LIBSRC)/X11

SOXLIBREV = 4
DEPXONLYLIB =
XONLYLIB =  -lX11

LINTXONLY = $(LINTLIBDIR)/llib-lX11.ln

         XLIBONLY = $(XONLYLIB)

      XEXTLIBSRC = $(LIBSRC)/Xext

SOXEXTREV = 0
DEPEXTENSIONLIB =
EXTENSIONLIB =  -lXext

LINTEXTENSION = $(LINTLIBDIR)/llib-lXext.ln

LINTEXTENSIONLIB = $(LINTEXTENSION)
          DEPXLIB = $(DEPEXTENSIONLIB) $(DEPXONLYLIB)
             XLIB = $(EXTENSIONLIB) $(XONLYLIB)
         LINTXLIB = $(LINTXONLYLIB)

         XAUTHSRC = $(LIBSRC)/Xau

DEPXAUTHLIB = $(USRLIBDIR)/libXau.a
XAUTHLIB =  -lXau

LINTXAUTH = $(LINTLIBDIR)/llib-lXau.ln

      XDMCPLIBSRC = $(LIBSRC)/Xdmcp

DEPXDMCPLIB = $(USRLIBDIR)/libXdmcp.a
XDMCPLIB =  -lXdmcp

LINTXDMCP = $(LINTLIBDIR)/llib-lXdmcp.ln

           XMUSRC = $(LIBSRC)/Xmu

SOXMUREV = 4
DEPXMULIB =
XMULIB =  -lXmu

LINTXMU = $(LINTLIBDIR)/llib-lXmu.ln

XMULIB =  -lXmu -lm

          XCONFIGSRC = $(LIBSRC)/Xconfig

SOXCONFIGREV = 0
DEPXCONFIGLIB =
XCONFIGLIB =  -lXconfig

LINTXCONFIG = $(LINTLIBDIR)/llib-lXconfig.ln

          DGASRC = $(LIBSRC)/dga

SODGAREV = 1
DEPDGASRCLIB =
DGASRCLIB =  -ldga

LINTDGASRC = $(LINTLIBDIR)/llib-ldga.ln

          MISRC = $(SERVERSRC)/mi

SOMIREV = 1
DEPMILIB =
MILIB =  -lmi

LINTMI = $(LINTLIBDIR)/llib-lmi.ln

          MFBSRC = $(SERVERSRC)/mfb

SOMFBREV = 1
DEPMFBLIB =
MFBLIB =  -lmfb

LINTMFB = $(LINTLIBDIR)/llib-lmfb.ln

          CFBSRC = $(SERVERSRC)/cfb

SOCFBREV = 1
DEPCFBLIB =
CFBLIB =  -lcfb

LINTCFB = $(LINTLIBDIR)/llib-lcfb.ln

       OLDXLIBSRC = $(LIBSRC)/oldX

SOOLDXREV = 6
DEPOLDXLIB =
OLDXLIB =  -loldX

LINTOLDX = $(LINTLIBDIR)/llib-loldX.ln

       TOOLKITSRC = $(LIBSRC)/Xt

SOXTREV = 4
DEPXTOOLONLYLIB =
XTOOLONLYLIB =  -lXt

LINTXTOOLONLY = $(LINTLIBDIR)/llib-lXt.ln

      DEPXTOOLLIB = $(DEPXTOOLONLYLIB) $(DEPSMLIB) $(DEPICELIB)
         XTOOLLIB = $(XTOOLONLYLIB) $(SMLIB) $(ICELIB)
     LINTXTOOLLIB = $(LINTXTOOLONLYLIB)

       AWIDGETSRC = $(LIBSRC)/Xaw

SOXAWREV = 5
DEPXAWLIB =
XAWLIB =  -lXaw

LINTXAW = $(LINTLIBDIR)/llib-lXaw.ln

       XTFSRC = $(TOP)/workInProgress/Xtf

SOXTFREV = 0.7
DEPXTFLIB =
XTFLIB =  -lXtf

LINTXTF = $(LINTLIBDIR)/llib-lXtf.ln

       FRESCOSRC = $(TOP)/workInProgress/Fresco

SOFRESCOREV = 0.7
DEPFRESCOLIB =
FRESCOLIB =  -lFresco

LINTFRESCO = $(LINTLIBDIR)/llib-lFresco.ln

         XILIBSRC = $(LIBSRC)/Xi

SOXINPUTREV = 5
DEPXILIB =
XILIB =  -lXi

LINTXI = $(LINTLIBDIR)/llib-lXi.ln

      XTESTLIBSRC = $(LIBSRC)/Xtst

SOXTESTREV = 1
DEPXTESTLIB =
XTESTLIB =  -lXtst

LINTXTEST = $(LINTLIBDIR)/llib-lXtst.ln

        PEXLIBSRC = $(LIBSRC)/PEX5

SOPEXREV = 6
DEPPEXLIB =
PEXLIB =  -lPEX5

LINTPEX = $(LINTLIBDIR)/llib-lPEX5.ln

SODPSREV = 5
SOSERVERDPSREV = 5

        DPSLIBSRC = $(LIBSRC)/DPS

SODPSREV = 5
DEPDPSLIB =
DPSLIB =  -lDPS

LINTDPS = $(LINTLIBDIR)/llib-lDPS.ln

        XIELIBSRC = $(LIBSRC)/XIE

SOXIEREV = 6
DEPXIELIB =
XIELIB =  -lXIE

LINTXIE = $(LINTLIBDIR)/llib-lXIE.ln

      PHIGSLIBSRC = $(LIBSRC)/PHIGS

DEPPHIGSLIB = $(USRLIBDIR)/libphigs.a
PHIGSLIB =  -lphigs

LINTPHIGS = $(LINTLIBDIR)/llib-lphigs.ln

DEPXBSDLIB = $(USRLIBDIR)/libXbsd.a
XBSDLIB =  -lXbsd

LINTXBSD = $(LINTLIBDIR)/llib-lXbsd.ln

           ICESRC = $(LIBSRC)/ICE

SOICEREV = 6
DEPICELIB =
ICELIB =  -lICE

LINTICE = $(LINTLIBDIR)/llib-lICE.ln

            SMSRC = $(LIBSRC)/SM

SOSMREV = 6
DEPSMLIB =
SMLIB =  -lSM

LINTSM = $(LINTLIBDIR)/llib-lSM.ln

         FSLIBSRC = $(LIBSRC)/FS

SOFSREV = 5
DEPFSLIB =
FSLIB =  -lFS

LINTFS = $(LINTLIBDIR)/llib-lFS.ln

         FONTLIBSRC = $(LIBSRC)/font

DEPFONTLIB = $(USRLIBDIR)/libfont.a
FONTLIB =  -lfont

LINTFONT = $(LINTLIBDIR)/llib-lfont.ln

    XRENDERLIBSRC = $(LIBSRC)/Xrender

SOXRENDERREV = 1
DEPXRENDERLIB =
XRENDERLIB =  -lXrender

LINTXRENDER = $(LINTLIBDIR)/llib-lXrender.ln

XRENDERLIB = -L/usr/openwin/sfw/lib -R/usr/openwin/lib:/usr/openwin/sfw/lib -lXrender

          DEPLIBS = $(DEPXAWLIB) $(DEPXMULIB) $(DEPXTOOLLIB) $(DEPXLIB)

         DEPLIBS1 = $(DEPLIBS)
         DEPLIBS2 = $(DEPLIBS)
         DEPLIBS3 = $(DEPLIBS)

        CONFIGDIR = $(LIBDIR)/config

# -----------------------------------------------------------------------
# start of Imakefile

#
# Here is an Imakefile for tvtwm.  The below defines for make are
# neccessary to have things work as expected, please don't remove
# any of them.
#

         YFLAGS = -d
        DEPLIBS = $(DEPXMULIB) $(DEPEXTENSIONLIB) $(DEPXLIB)

#	This symbol is to make m4 be used to preprocess your .[tv]twmrc
# file through m4 by default.  Set to 0, you need to use the -m
# runtime option to make it use m4.

#   If you have flex as your $(LEX), (or a lex that *is* flex, like
# on many x86 BSD boxes) then you need to add the -l argument to cause
# the maximum level of compatibility with AT&T lex.  In particular, it
# will define yylineno.  If you get an "Undefined symbol: _yylineno"
# when linking, adjust this to work on your system.

#   If you don't have waitpid(), you're kinda out of luck.  tvtwm
# will leave zombie processes around, cause there's no safe way to
# wait for them without waitpid().  So, if you define this symbol,
# tvtwm will build just dandy without waitpid(), but will leave
# zombies.  (*sigh*)  Oh well.  Better than nothing.

#
#   Any of these three lines can be commented out.  The first two are
# for Xpm support.  If you do not wish to use the Xpm library functions,
# comment these two lines out.  The last line is for support to allow
# the xloadimage program by Jim Frost to perform your background loading.
# (thus allowing loading of other image formats besides Xpm or Xbm)
#                                 Chris P. Ross
#                                 <cross@eng.umd.edu>
#
#   Also note, if you install your libXpm.a in a strange place, you'll
# have to adjust $(XPMLIB) below.  You may also have to change the
# include path of the compile, so that the code can include from
# <X11/xpm.h>.
#

         XPMLIB = -lXpm
        XPM_DEF = -DXPM
    XLOADIM_DEF = -DXLOADIMAGE=\"$(TWMDIR)/xloadimage\"

#   Ultrix doesn't have a mkstemp in libc...
#   Sys V doesn't seem to either...

  LOCAL_DEFINES = $(XPM_DEF)

#   Various defines to pass into twm.c

         M4_DEF = -DM4_DEFAULT

       TWM_DEFS = $(XLOADIM_DEF) $(M4_DEF) $(WAITPID_DEF)

LOCAL_LIBRARIES = $(XMULIB) $(EXTENSIONLIB) $(XPMLIB) $(XLIB)
       LINTLIBS = $(LINTXMU) $(LINTEXTENSIONLIB) $(LINTXLIB)
        DEFINES = -DSHAPE $(RELEASE_DEFINES) $(LOCAL_DEFINES) $(SIGNAL_DEFINES)

           SRCS = gram.c lex.c deftwmrc.c add_window.c gc.c list.c twm.c \
                  parse.c menus.c events.c resize.c util.c version.c \
                  iconmgr.c cursor.c icons.c vdt.c move.c LocPixmap.c \
                  regexp.c

           OBJS = gram.o lex.o deftwmrc.o add_window.o gc.o list.o twm.o \
                  parse.o menus.o events.o resize.o util.o version.o \
                  iconmgr.o cursor.o icons.o vdt.o move.o LocPixmap.o \
                  regexp.o

all:: tvtwm ssetroot

parse.o:
	$(RM) $@
	$(CC) -c $(CFLAGS) '-DSYSTEM_INIT_DIR="'$(TWMDIR)'"' $*.c

vdt.o:
	$(RM) $@
	$(CC) -c $(CFLAGS) $(XLOADIM_DEF) $*.c

LocPixmap.o:
	$(RM) $@
	$(CC) -c $(CFLAGS) '-DBITMAPDIR="$(INCDIR)/bitmaps"' $*.c

twm.o:
	$(RM) $@
	$(CC) -c $(CFLAGS) $(TWM_DEFS) $*.c

depend:: lex.c gram.c deftwmrc.c

 PROGRAM = tvtwm

all:: tvtwm

tvtwm: $(OBJS) $(DEPLIBS)
	$(RM) $@
	$(CCLINK) -o $@ $(LDOPTIONS) $(OBJS) $(LOCAL_LIBRARIES) $(LDLIBS)  $(EXTRA_LOAD_FLAGS)

install:: tvtwm
	@if [ -d $(DESTDIR)$(BINDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(BINDIR)); fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTPGMFLAGS)  tvtwm $(DESTDIR)$(BINDIR)/tvtwm

install.man:: tvtwm.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTMANFLAGS) tvtwm.man $(DESTDIR)$(MANDIR)/tvtwm.$(MANSUFFIX)

depend::
	$(DEPEND) $(DEPENDFLAGS) -- $(ALLDEFINES) $(DEPEND_DEFINES) -- $(SRCS)

lint:
	$(LINT) $(LINTFLAGS) $(SRCS) $(LINTLIBS)
lint1:
	$(LINT) $(LINTFLAGS) $(FILE) $(LINTLIBS)

clean::
	$(RM) tvtwm

ssetroot: ssetroot.o
	$(RM) $@
	$(CCLINK) -o $@ $(LDOPTIONS) ssetroot.o $(LOCAL_LIBRARIES) $(LDLIBS)  $(EXTRA_LOAD_FLAGS)

clean::
	$(RM) ssetroot

# This will have a link called twm installed linked to tvtwm

# install::
#	rm -f $(BINDIR)/twm
#	ln $(BINDIR)/tvtwm $(BINDIR)/twm

install:: system.twmrc
	@if [ -d $(DESTDIR)$(TWMDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(TWMDIR)); fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTDATFLAGS) system.twmrc $(DESTDIR)$(TWMDIR)/system.twmrc

gram.h gram.c: gram.y
	$(YACC) $(YFLAGS) gram.y
	$(MV) y.tab.c gram.c
	$(MV) y.tab.h gram.h

clean::
	$(RM) y.tab.h y.tab.c lex.yy.c gram.h gram.c lex.c deftwmrc.c

deftwmrc.c:  system.twmrc
	$(RM) $@
	@echo '/* ' >>$@
	@echo ' * This file is generated automatically from the default' >>$@
	@echo ' * twm bindings file system.twmrc by the twm Imakefile.' >>$@
	@echo ' */' >>$@
	@echo '' >>$@
	@echo 'char *defTwmrc[] = {' >>$@
	sed -e '/^#/d' -e 's/"/\\"/g' -e 's/^/    "/' -e 's/$$/",/' \
		system.twmrc >>$@
	@echo '    (char *) 0 };' >>$@

# -----------------------------------------------------------------------
# common rules for all Makefiles - do not edit

.c.i:
	$(RM) $@
	$(CC) -E $(CFLAGS) $(_NOOP_) $*.c > $@

emptyrule::

clean::
	$(RM) *.CKP *.ln *.BAK *.bak *.o core errs ,* *~ *.a .emacs_* tags TAGS make.log MakeOut   "#"*

Makefile::
	-@if [ -f Makefile ]; then set -x; \
	$(RM) Makefile.bak; $(MV) Makefile Makefile.bak; \
	else exit 0; fi
	$(IMAKE_CMD) -DTOPDIR=$(TOP) -DCURDIR=$(CURRENT_DIR)

tags::
	$(TAGS) -w *.[ch]
	$(TAGS) -xw *.[ch] > TAGS

man_keywords::
	catman -M $(DESTDIR)$(MANPATH) -w

# ----------------------------------------------------------------------
# empty rules for directories that do not have SUBDIRS - do not edit

install::
	@echo "install in $(CURRENT_DIR) done"

install.man::
	@echo "install.man in $(CURRENT_DIR) done"

Makefiles::

includes::

depend::

# -----------------------------------------------------------------------
# dependencies generated by makedepend

# DO NOT DELETE

gram.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
gram.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
gram.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
gram.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
gram.o: /usr/include/iso/stdio_c99.h /usr/include/ctype.h
gram.o: /usr/include/iso/ctype_iso.h /usr/include/iso/ctype_c99.h twm.h
gram.o: /usr/openwin/include/X11/Intrinsic.h /usr/openwin/include/X11/Xlib.h
gram.o: /usr/include/sys/types.h /usr/include/sys/machtypes.h
gram.o: /usr/include/ia32/sys/machtypes.h /usr/include/sys/int_types.h
gram.o: /usr/include/sys/select.h /usr/include/sys/time_impl.h
gram.o: /usr/include/sys/time.h /usr/include/sys/time.h
gram.o: /usr/openwin/include/X11/X.h /usr/openwin/include/X11/Xfuncproto.h
gram.o: /usr/openwin/include/X11/Xosdefs.h /usr/include/stddef.h
gram.o: /usr/include/iso/stddef_iso.h /usr/openwin/include/X11/Xutil.h
gram.o: /usr/openwin/include/X11/Xresource.h /usr/include/string.h
gram.o: /usr/include/iso/string_iso.h /usr/openwin/include/X11/Core.h
gram.o: /usr/openwin/include/X11/Composite.h
gram.o: /usr/openwin/include/X11/Constraint.h
gram.o: /usr/openwin/include/X11/Object.h /usr/openwin/include/X11/RectObj.h
gram.o: /usr/openwin/include/X11/cursorfont.h
gram.o: /usr/openwin/include/X11/extensions/shape.h
gram.o: /usr/openwin/include/X11/Xfuncs.h /usr/include/strings.h
gram.o: /usr/openwin/include/X11/xpm.h icons.h /usr/include/stdlib.h
gram.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h menus.h
gram.o: list.h util.h screen.h iconmgr.h parse.h
gram.o: /usr/openwin/include/X11/Xos.h /usr/include/fcntl.h
gram.o: /usr/include/sys/fcntl.h /usr/include/unistd.h
gram.o: /usr/include/sys/unistd.h /usr/openwin/include/X11/Xmu/CharSet.h
gram.o: /usr/include/inttypes.h /usr/include/sys/inttypes.h
gram.o: /usr/include/sys/int_limits.h /usr/include/sys/int_const.h
gram.o: /usr/include/sys/int_fmtio.h /usr/include/sys/stdint.h
gram.o: /usr/include/values.h
lex.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
lex.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
lex.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
lex.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
lex.o: /usr/include/iso/stdio_c99.h /usr/include/stdlib.h
lex.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h
lex.o: /usr/include/inttypes.h /usr/include/sys/inttypes.h
lex.o: /usr/include/sys/int_types.h /usr/include/sys/int_limits.h
lex.o: /usr/include/sys/int_const.h /usr/include/sys/int_fmtio.h
lex.o: /usr/include/sys/stdint.h gram.h parse.h
add_window.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
add_window.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
add_window.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
add_window.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
add_window.o: /usr/include/iso/stdio_c99.h twm.h
add_window.o: /usr/openwin/include/X11/Intrinsic.h
add_window.o: /usr/openwin/include/X11/Xlib.h /usr/include/sys/types.h
add_window.o: /usr/include/sys/machtypes.h /usr/include/ia32/sys/machtypes.h
add_window.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
add_window.o: /usr/include/sys/time_impl.h /usr/include/sys/time.h
add_window.o: /usr/include/sys/time.h /usr/openwin/include/X11/X.h
add_window.o: /usr/openwin/include/X11/Xfuncproto.h
add_window.o: /usr/openwin/include/X11/Xosdefs.h /usr/include/stddef.h
add_window.o: /usr/include/iso/stddef_iso.h /usr/openwin/include/X11/Xutil.h
add_window.o: /usr/openwin/include/X11/Xresource.h /usr/include/string.h
add_window.o: /usr/include/iso/string_iso.h /usr/openwin/include/X11/Core.h
add_window.o: /usr/openwin/include/X11/Composite.h
add_window.o: /usr/openwin/include/X11/Constraint.h
add_window.o: /usr/openwin/include/X11/Object.h
add_window.o: /usr/openwin/include/X11/RectObj.h
add_window.o: /usr/openwin/include/X11/cursorfont.h
add_window.o: /usr/openwin/include/X11/extensions/shape.h
add_window.o: /usr/openwin/include/X11/Xfuncs.h /usr/include/strings.h
add_window.o: /usr/openwin/include/X11/xpm.h icons.h /usr/include/stdlib.h
add_window.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h
add_window.o: /usr/openwin/include/X11/Xatom.h
add_window.o: /usr/openwin/include/X11/Xmu/Drawing.h add_window.h util.h
add_window.o: resize.h parse.h list.h events.h menus.h screen.h iconmgr.h
add_window.o: move.h vdt.h
gc.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
gc.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
gc.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
gc.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
gc.o: /usr/include/iso/stdio_c99.h twm.h /usr/openwin/include/X11/Intrinsic.h
gc.o: /usr/openwin/include/X11/Xlib.h /usr/include/sys/types.h
gc.o: /usr/include/sys/machtypes.h /usr/include/ia32/sys/machtypes.h
gc.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
gc.o: /usr/include/sys/time_impl.h /usr/include/sys/time.h
gc.o: /usr/include/sys/time.h /usr/openwin/include/X11/X.h
gc.o: /usr/openwin/include/X11/Xfuncproto.h
gc.o: /usr/openwin/include/X11/Xosdefs.h /usr/include/stddef.h
gc.o: /usr/include/iso/stddef_iso.h /usr/openwin/include/X11/Xutil.h
gc.o: /usr/openwin/include/X11/Xresource.h /usr/include/string.h
gc.o: /usr/include/iso/string_iso.h /usr/openwin/include/X11/Core.h
gc.o: /usr/openwin/include/X11/Composite.h
gc.o: /usr/openwin/include/X11/Constraint.h /usr/openwin/include/X11/Object.h
gc.o: /usr/openwin/include/X11/RectObj.h
gc.o: /usr/openwin/include/X11/cursorfont.h
gc.o: /usr/openwin/include/X11/extensions/shape.h
gc.o: /usr/openwin/include/X11/Xfuncs.h /usr/include/strings.h
gc.o: /usr/openwin/include/X11/xpm.h icons.h /usr/include/stdlib.h
gc.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h util.h
gc.o: screen.h list.h menus.h iconmgr.h
list.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
list.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
list.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
list.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
list.o: /usr/include/iso/stdio_c99.h /usr/openwin/include/X11/Xatom.h twm.h
list.o: /usr/openwin/include/X11/Intrinsic.h /usr/openwin/include/X11/Xlib.h
list.o: /usr/include/sys/types.h /usr/include/sys/machtypes.h
list.o: /usr/include/ia32/sys/machtypes.h /usr/include/sys/int_types.h
list.o: /usr/include/sys/select.h /usr/include/sys/time_impl.h
list.o: /usr/include/sys/time.h /usr/include/sys/time.h
list.o: /usr/openwin/include/X11/X.h /usr/openwin/include/X11/Xfuncproto.h
list.o: /usr/openwin/include/X11/Xosdefs.h /usr/include/stddef.h
list.o: /usr/include/iso/stddef_iso.h /usr/openwin/include/X11/Xutil.h
list.o: /usr/openwin/include/X11/Xresource.h /usr/include/string.h
list.o: /usr/include/iso/string_iso.h /usr/openwin/include/X11/Core.h
list.o: /usr/openwin/include/X11/Composite.h
list.o: /usr/openwin/include/X11/Constraint.h
list.o: /usr/openwin/include/X11/Object.h /usr/openwin/include/X11/RectObj.h
list.o: /usr/openwin/include/X11/cursorfont.h
list.o: /usr/openwin/include/X11/extensions/shape.h
list.o: /usr/openwin/include/X11/Xfuncs.h /usr/include/strings.h
list.o: /usr/openwin/include/X11/xpm.h icons.h /usr/include/stdlib.h
list.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h screen.h
list.o: list.h menus.h iconmgr.h gram.h util.h regexp.h
twm.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
twm.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
twm.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
twm.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
twm.o: /usr/include/iso/stdio_c99.h /usr/include/signal.h
twm.o: /usr/include/iso/signal_iso.h /usr/include/sys/iso/signal_iso.h
twm.o: /usr/include/sys/unistd.h /usr/include/sys/signal.h
twm.o: /usr/include/fcntl.h /usr/include/sys/types.h
twm.o: /usr/include/sys/machtypes.h /usr/include/ia32/sys/machtypes.h
twm.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
twm.o: /usr/include/sys/time_impl.h /usr/include/sys/time.h
twm.o: /usr/include/sys/time.h /usr/include/sys/fcntl.h
twm.o: /usr/include/sys/wait.h /usr/include/sys/resource.h
twm.o: /usr/include/sys/siginfo.h /usr/include/sys/machsig.h
twm.o: /usr/include/vm/faultcode.h /usr/include/sys/procset.h twm.h
twm.o: /usr/openwin/include/X11/Intrinsic.h /usr/openwin/include/X11/Xlib.h
twm.o: /usr/openwin/include/X11/X.h /usr/openwin/include/X11/Xfuncproto.h
twm.o: /usr/openwin/include/X11/Xosdefs.h /usr/include/stddef.h
twm.o: /usr/include/iso/stddef_iso.h /usr/openwin/include/X11/Xutil.h
twm.o: /usr/openwin/include/X11/Xresource.h /usr/include/string.h
twm.o: /usr/include/iso/string_iso.h /usr/openwin/include/X11/Core.h
twm.o: /usr/openwin/include/X11/Composite.h
twm.o: /usr/openwin/include/X11/Constraint.h
twm.o: /usr/openwin/include/X11/Object.h /usr/openwin/include/X11/RectObj.h
twm.o: /usr/openwin/include/X11/cursorfont.h
twm.o: /usr/openwin/include/X11/extensions/shape.h
twm.o: /usr/openwin/include/X11/Xfuncs.h /usr/include/strings.h
twm.o: /usr/openwin/include/X11/xpm.h icons.h /usr/include/stdlib.h
twm.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h
twm.o: add_window.h gc.h parse.h version.h menus.h events.h util.h gram.h
twm.o: screen.h list.h iconmgr.h /usr/openwin/include/X11/Xproto.h
twm.o: /usr/openwin/include/X11/Xmd.h /usr/openwin/include/X11/Xprotostr.h
twm.o: /usr/openwin/include/X11/Xatom.h
twm.o: /usr/openwin/include/X11/bitmaps/root_weave vdt.h
twm.o: /usr/openwin/include/X11/keysymdef.h
twm.o: /usr/openwin/include/X11/Xmu/Error.h
parse.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
parse.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
parse.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
parse.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
parse.o: /usr/include/iso/stdio_c99.h /usr/include/ctype.h
parse.o: /usr/include/iso/ctype_iso.h /usr/include/iso/ctype_c99.h
parse.o: /usr/include/errno.h /usr/include/sys/errno.h
parse.o: /usr/openwin/include/X11/Xos.h /usr/openwin/include/X11/Xosdefs.h
parse.o: /usr/include/sys/types.h /usr/include/sys/machtypes.h
parse.o: /usr/include/ia32/sys/machtypes.h /usr/include/sys/int_types.h
parse.o: /usr/include/sys/select.h /usr/include/sys/time_impl.h
parse.o: /usr/include/sys/time.h /usr/include/sys/time.h
parse.o: /usr/openwin/include/X11/Xfuncs.h /usr/include/strings.h
parse.o: /usr/include/string.h /usr/include/iso/string_iso.h
parse.o: /usr/include/fcntl.h /usr/include/sys/fcntl.h /usr/include/unistd.h
parse.o: /usr/include/sys/unistd.h /usr/openwin/include/X11/Xmu/CharSet.h
parse.o: /usr/openwin/include/X11/Xfuncproto.h
parse.o: /usr/openwin/include/X11/Xmu/SysUtil.h twm.h
parse.o: /usr/openwin/include/X11/Intrinsic.h /usr/openwin/include/X11/Xlib.h
parse.o: /usr/openwin/include/X11/X.h /usr/include/stddef.h
parse.o: /usr/include/iso/stddef_iso.h /usr/openwin/include/X11/Xutil.h
parse.o: /usr/openwin/include/X11/Xresource.h /usr/openwin/include/X11/Core.h
parse.o: /usr/openwin/include/X11/Composite.h
parse.o: /usr/openwin/include/X11/Constraint.h
parse.o: /usr/openwin/include/X11/Object.h /usr/openwin/include/X11/RectObj.h
parse.o: /usr/openwin/include/X11/cursorfont.h
parse.o: /usr/openwin/include/X11/extensions/shape.h
parse.o: /usr/openwin/include/X11/xpm.h icons.h /usr/include/stdlib.h
parse.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h screen.h
parse.o: list.h menus.h iconmgr.h util.h gram.h parse.h
parse.o: /usr/openwin/include/X11/Xatom.h vdt.h /usr/include/sys/param.h
parse.o: /usr/include/sys/socket.h /usr/include/sys/uio.h
parse.o: /usr/include/sys/socket_impl.h /usr/include/sys/un.h
parse.o: /usr/include/net/if_dl.h /usr/include/sys/netconfig.h
parse.o: /usr/include/netinet/in.h /usr/include/sys/stream.h
parse.o: /usr/include/sys/vnode.h /usr/include/sys/t_lock.h
parse.o: /usr/include/sys/machlock.h /usr/include/sys/mutex.h
parse.o: /usr/include/sys/rwlock.h /usr/include/sys/semaphore.h
parse.o: /usr/include/sys/condvar.h /usr/include/sys/rwstlock.h
parse.o: /usr/include/sys/ksynch.h /usr/include/sys/cred.h
parse.o: /usr/include/sys/resource.h /usr/include/vm/seg_enum.h
parse.o: /usr/include/sys/kstat.h /usr/include/sys/kmem.h
parse.o: /usr/include/sys/vmem.h /usr/include/sys/poll.h
parse.o: /usr/include/sys/strmdep.h /usr/include/sys/model.h
parse.o: /usr/include/sys/strft.h /usr/include/sys/byteorder.h
parse.o: /usr/include/netdb.h
menus.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
menus.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
menus.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
menus.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
menus.o: /usr/include/iso/stdio_c99.h /usr/include/signal.h
menus.o: /usr/include/iso/signal_iso.h /usr/include/sys/iso/signal_iso.h
menus.o: /usr/include/sys/unistd.h /usr/include/sys/signal.h
menus.o: /usr/include/sys/types.h /usr/include/sys/machtypes.h
menus.o: /usr/include/ia32/sys/machtypes.h /usr/include/sys/int_types.h
menus.o: /usr/include/sys/select.h /usr/include/sys/time_impl.h
menus.o: /usr/include/sys/time.h /usr/include/sys/time.h
menus.o: /usr/include/sys/stat.h /usr/include/sys/stat_impl.h
menus.o: /usr/openwin/include/X11/Xos.h /usr/openwin/include/X11/Xosdefs.h
menus.o: /usr/openwin/include/X11/Xfuncs.h /usr/include/strings.h
menus.o: /usr/include/string.h /usr/include/iso/string_iso.h
menus.o: /usr/include/fcntl.h /usr/include/sys/fcntl.h /usr/include/unistd.h
menus.o: /usr/openwin/include/X11/Xatom.h twm.h
menus.o: /usr/openwin/include/X11/Intrinsic.h /usr/openwin/include/X11/Xlib.h
menus.o: /usr/openwin/include/X11/X.h /usr/openwin/include/X11/Xfuncproto.h
menus.o: /usr/include/stddef.h /usr/include/iso/stddef_iso.h
menus.o: /usr/openwin/include/X11/Xutil.h
menus.o: /usr/openwin/include/X11/Xresource.h /usr/openwin/include/X11/Core.h
menus.o: /usr/openwin/include/X11/Composite.h
menus.o: /usr/openwin/include/X11/Constraint.h
menus.o: /usr/openwin/include/X11/Object.h /usr/openwin/include/X11/RectObj.h
menus.o: /usr/openwin/include/X11/cursorfont.h
menus.o: /usr/openwin/include/X11/extensions/shape.h
menus.o: /usr/openwin/include/X11/xpm.h icons.h /usr/include/stdlib.h
menus.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h gc.h
menus.o: menus.h resize.h events.h util.h parse.h gram.h screen.h list.h
menus.o: iconmgr.h /usr/openwin/include/X11/Xmu/CharSet.h
menus.o: /usr/openwin/include/X11/Xmu/Drawing.h version.h vdt.h add_window.h
menus.o: patchlevel.h /usr/include/math.h /usr/include/iso/math_iso.h
menus.o: /usr/include/iso/math_c99.h emblem.h
events.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
events.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
events.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
events.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
events.o: /usr/include/iso/stdio_c99.h twm.h
events.o: /usr/openwin/include/X11/Intrinsic.h
events.o: /usr/openwin/include/X11/Xlib.h /usr/include/sys/types.h
events.o: /usr/include/sys/machtypes.h /usr/include/ia32/sys/machtypes.h
events.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
events.o: /usr/include/sys/time_impl.h /usr/include/sys/time.h
events.o: /usr/include/sys/time.h /usr/openwin/include/X11/X.h
events.o: /usr/openwin/include/X11/Xfuncproto.h
events.o: /usr/openwin/include/X11/Xosdefs.h /usr/include/stddef.h
events.o: /usr/include/iso/stddef_iso.h /usr/openwin/include/X11/Xutil.h
events.o: /usr/openwin/include/X11/Xresource.h /usr/include/string.h
events.o: /usr/include/iso/string_iso.h /usr/openwin/include/X11/Core.h
events.o: /usr/openwin/include/X11/Composite.h
events.o: /usr/openwin/include/X11/Constraint.h
events.o: /usr/openwin/include/X11/Object.h
events.o: /usr/openwin/include/X11/RectObj.h
events.o: /usr/openwin/include/X11/cursorfont.h
events.o: /usr/openwin/include/X11/extensions/shape.h
events.o: /usr/openwin/include/X11/Xfuncs.h /usr/include/strings.h
events.o: /usr/openwin/include/X11/xpm.h icons.h /usr/include/stdlib.h
events.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h
events.o: /usr/openwin/include/X11/Xatom.h add_window.h menus.h events.h
events.o: resize.h parse.h gram.h util.h screen.h list.h iconmgr.h version.h
events.o: vdt.h
resize.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
resize.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
resize.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
resize.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
resize.o: /usr/include/iso/stdio_c99.h twm.h
resize.o: /usr/openwin/include/X11/Intrinsic.h
resize.o: /usr/openwin/include/X11/Xlib.h /usr/include/sys/types.h
resize.o: /usr/include/sys/machtypes.h /usr/include/ia32/sys/machtypes.h
resize.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
resize.o: /usr/include/sys/time_impl.h /usr/include/sys/time.h
resize.o: /usr/include/sys/time.h /usr/openwin/include/X11/X.h
resize.o: /usr/openwin/include/X11/Xfuncproto.h
resize.o: /usr/openwin/include/X11/Xosdefs.h /usr/include/stddef.h
resize.o: /usr/include/iso/stddef_iso.h /usr/openwin/include/X11/Xutil.h
resize.o: /usr/openwin/include/X11/Xresource.h /usr/include/string.h
resize.o: /usr/include/iso/string_iso.h /usr/openwin/include/X11/Core.h
resize.o: /usr/openwin/include/X11/Composite.h
resize.o: /usr/openwin/include/X11/Constraint.h
resize.o: /usr/openwin/include/X11/Object.h
resize.o: /usr/openwin/include/X11/RectObj.h
resize.o: /usr/openwin/include/X11/cursorfont.h
resize.o: /usr/openwin/include/X11/extensions/shape.h
resize.o: /usr/openwin/include/X11/Xfuncs.h /usr/include/strings.h
resize.o: /usr/openwin/include/X11/xpm.h icons.h /usr/include/stdlib.h
resize.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h parse.h
resize.o: util.h resize.h add_window.h screen.h list.h menus.h iconmgr.h
resize.o: vdt.h
util.o: twm.h /usr/openwin/include/X11/Intrinsic.h
util.o: /usr/openwin/include/X11/Xlib.h /usr/include/sys/types.h
util.o: /usr/include/sys/feature_tests.h /usr/include/sys/ccompile.h
util.o: /usr/include/sys/isa_defs.h /usr/include/sys/machtypes.h
util.o: /usr/include/ia32/sys/machtypes.h /usr/include/sys/int_types.h
util.o: /usr/include/sys/select.h /usr/include/sys/time_impl.h
util.o: /usr/include/sys/time.h /usr/include/sys/time.h
util.o: /usr/openwin/include/X11/X.h /usr/openwin/include/X11/Xfuncproto.h
util.o: /usr/openwin/include/X11/Xosdefs.h /usr/include/stddef.h
util.o: /usr/include/iso/stddef_iso.h /usr/openwin/include/X11/Xutil.h
util.o: /usr/openwin/include/X11/Xresource.h /usr/include/string.h
util.o: /usr/include/iso/string_iso.h /usr/openwin/include/X11/Core.h
util.o: /usr/openwin/include/X11/Composite.h
util.o: /usr/openwin/include/X11/Constraint.h
util.o: /usr/openwin/include/X11/Object.h /usr/openwin/include/X11/RectObj.h
util.o: /usr/openwin/include/X11/cursorfont.h
util.o: /usr/openwin/include/X11/extensions/shape.h
util.o: /usr/openwin/include/X11/Xfuncs.h /usr/include/strings.h
util.o: /usr/openwin/include/X11/xpm.h icons.h /usr/include/stdlib.h
util.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h util.h
util.o: gram.h screen.h list.h menus.h iconmgr.h
util.o: /usr/openwin/include/X11/Xos.h /usr/include/fcntl.h
util.o: /usr/include/sys/fcntl.h /usr/include/unistd.h
util.o: /usr/include/sys/unistd.h /usr/openwin/include/X11/Xatom.h
util.o: /usr/include/stdio.h /usr/include/iso/stdio_iso.h
util.o: /usr/include/sys/va_list.h /usr/include/stdio_tag.h
util.o: /usr/include/stdio_impl.h /usr/include/iso/stdio_c99.h
util.o: /usr/openwin/include/X11/Xmu/Drawing.h
util.o: /usr/openwin/include/X11/Xmu/CharSet.h
iconmgr.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
iconmgr.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
iconmgr.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
iconmgr.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
iconmgr.o: /usr/include/iso/stdio_c99.h twm.h
iconmgr.o: /usr/openwin/include/X11/Intrinsic.h
iconmgr.o: /usr/openwin/include/X11/Xlib.h /usr/include/sys/types.h
iconmgr.o: /usr/include/sys/machtypes.h /usr/include/ia32/sys/machtypes.h
iconmgr.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
iconmgr.o: /usr/include/sys/time_impl.h /usr/include/sys/time.h
iconmgr.o: /usr/include/sys/time.h /usr/openwin/include/X11/X.h
iconmgr.o: /usr/openwin/include/X11/Xfuncproto.h
iconmgr.o: /usr/openwin/include/X11/Xosdefs.h /usr/include/stddef.h
iconmgr.o: /usr/include/iso/stddef_iso.h /usr/openwin/include/X11/Xutil.h
iconmgr.o: /usr/openwin/include/X11/Xresource.h /usr/include/string.h
iconmgr.o: /usr/include/iso/string_iso.h /usr/openwin/include/X11/Core.h
iconmgr.o: /usr/openwin/include/X11/Composite.h
iconmgr.o: /usr/openwin/include/X11/Constraint.h
iconmgr.o: /usr/openwin/include/X11/Object.h
iconmgr.o: /usr/openwin/include/X11/RectObj.h
iconmgr.o: /usr/openwin/include/X11/cursorfont.h
iconmgr.o: /usr/openwin/include/X11/extensions/shape.h
iconmgr.o: /usr/openwin/include/X11/Xfuncs.h /usr/include/strings.h
iconmgr.o: /usr/openwin/include/X11/xpm.h icons.h /usr/include/stdlib.h
iconmgr.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h util.h
iconmgr.o: parse.h screen.h list.h menus.h iconmgr.h resize.h add_window.h
iconmgr.o: siconify.bm vdt.h /usr/openwin/include/X11/Xos.h
iconmgr.o: /usr/include/fcntl.h /usr/include/sys/fcntl.h
iconmgr.o: /usr/include/unistd.h /usr/include/sys/unistd.h
iconmgr.o: /usr/openwin/include/X11/Xmu/CharSet.h
cursor.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
cursor.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
cursor.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
cursor.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
cursor.o: /usr/include/iso/stdio_c99.h twm.h
cursor.o: /usr/openwin/include/X11/Intrinsic.h
cursor.o: /usr/openwin/include/X11/Xlib.h /usr/include/sys/types.h
cursor.o: /usr/include/sys/machtypes.h /usr/include/ia32/sys/machtypes.h
cursor.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
cursor.o: /usr/include/sys/time_impl.h /usr/include/sys/time.h
cursor.o: /usr/include/sys/time.h /usr/openwin/include/X11/X.h
cursor.o: /usr/openwin/include/X11/Xfuncproto.h
cursor.o: /usr/openwin/include/X11/Xosdefs.h /usr/include/stddef.h
cursor.o: /usr/include/iso/stddef_iso.h /usr/openwin/include/X11/Xutil.h
cursor.o: /usr/openwin/include/X11/Xresource.h /usr/include/string.h
cursor.o: /usr/include/iso/string_iso.h /usr/openwin/include/X11/Core.h
cursor.o: /usr/openwin/include/X11/Composite.h
cursor.o: /usr/openwin/include/X11/Constraint.h
cursor.o: /usr/openwin/include/X11/Object.h
cursor.o: /usr/openwin/include/X11/RectObj.h
cursor.o: /usr/openwin/include/X11/cursorfont.h
cursor.o: /usr/openwin/include/X11/extensions/shape.h
cursor.o: /usr/openwin/include/X11/Xfuncs.h /usr/include/strings.h
cursor.o: /usr/openwin/include/X11/xpm.h icons.h /usr/include/stdlib.h
cursor.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h
cursor.o: /usr/openwin/include/X11/Xos.h /usr/include/fcntl.h
cursor.o: /usr/include/sys/fcntl.h /usr/include/unistd.h
cursor.o: /usr/include/sys/unistd.h screen.h list.h menus.h iconmgr.h util.h
icons.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
icons.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
icons.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
icons.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
icons.o: /usr/include/iso/stdio_c99.h twm.h
icons.o: /usr/openwin/include/X11/Intrinsic.h /usr/openwin/include/X11/Xlib.h
icons.o: /usr/include/sys/types.h /usr/include/sys/machtypes.h
icons.o: /usr/include/ia32/sys/machtypes.h /usr/include/sys/int_types.h
icons.o: /usr/include/sys/select.h /usr/include/sys/time_impl.h
icons.o: /usr/include/sys/time.h /usr/include/sys/time.h
icons.o: /usr/openwin/include/X11/X.h /usr/openwin/include/X11/Xfuncproto.h
icons.o: /usr/openwin/include/X11/Xosdefs.h /usr/include/stddef.h
icons.o: /usr/include/iso/stddef_iso.h /usr/openwin/include/X11/Xutil.h
icons.o: /usr/openwin/include/X11/Xresource.h /usr/include/string.h
icons.o: /usr/include/iso/string_iso.h /usr/openwin/include/X11/Core.h
icons.o: /usr/openwin/include/X11/Composite.h
icons.o: /usr/openwin/include/X11/Constraint.h
icons.o: /usr/openwin/include/X11/Object.h /usr/openwin/include/X11/RectObj.h
icons.o: /usr/openwin/include/X11/cursorfont.h
icons.o: /usr/openwin/include/X11/extensions/shape.h
icons.o: /usr/openwin/include/X11/Xfuncs.h /usr/include/strings.h
icons.o: /usr/openwin/include/X11/xpm.h icons.h /usr/include/stdlib.h
icons.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h screen.h
icons.o: list.h menus.h iconmgr.h gram.h parse.h util.h vdt.h
vdt.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
vdt.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
vdt.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
vdt.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
vdt.o: /usr/include/iso/stdio_c99.h /usr/include/unistd.h
vdt.o: /usr/include/sys/types.h /usr/include/sys/machtypes.h
vdt.o: /usr/include/ia32/sys/machtypes.h /usr/include/sys/int_types.h
vdt.o: /usr/include/sys/select.h /usr/include/sys/time_impl.h
vdt.o: /usr/include/sys/time.h /usr/include/sys/time.h
vdt.o: /usr/include/sys/unistd.h /usr/openwin/include/X11/X.h
vdt.o: /usr/openwin/include/X11/Xatom.h twm.h
vdt.o: /usr/openwin/include/X11/Intrinsic.h /usr/openwin/include/X11/Xlib.h
vdt.o: /usr/openwin/include/X11/Xfuncproto.h
vdt.o: /usr/openwin/include/X11/Xosdefs.h /usr/include/stddef.h
vdt.o: /usr/include/iso/stddef_iso.h /usr/openwin/include/X11/Xutil.h
vdt.o: /usr/openwin/include/X11/Xresource.h /usr/include/string.h
vdt.o: /usr/include/iso/string_iso.h /usr/openwin/include/X11/Core.h
vdt.o: /usr/openwin/include/X11/Composite.h
vdt.o: /usr/openwin/include/X11/Constraint.h
vdt.o: /usr/openwin/include/X11/Object.h /usr/openwin/include/X11/RectObj.h
vdt.o: /usr/openwin/include/X11/cursorfont.h
vdt.o: /usr/openwin/include/X11/extensions/shape.h
vdt.o: /usr/openwin/include/X11/Xfuncs.h /usr/include/strings.h
vdt.o: /usr/openwin/include/X11/xpm.h icons.h /usr/include/stdlib.h
vdt.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h screen.h
vdt.o: list.h menus.h iconmgr.h vdt.h parse.h move.h util.h resize.h
move.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
move.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
move.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
move.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
move.o: /usr/include/iso/stdio_c99.h /usr/openwin/include/X11/X.h
move.o: /usr/openwin/include/X11/Xatom.h twm.h
move.o: /usr/openwin/include/X11/Intrinsic.h /usr/openwin/include/X11/Xlib.h
move.o: /usr/include/sys/types.h /usr/include/sys/machtypes.h
move.o: /usr/include/ia32/sys/machtypes.h /usr/include/sys/int_types.h
move.o: /usr/include/sys/select.h /usr/include/sys/time_impl.h
move.o: /usr/include/sys/time.h /usr/include/sys/time.h
move.o: /usr/openwin/include/X11/Xfuncproto.h
move.o: /usr/openwin/include/X11/Xosdefs.h /usr/include/stddef.h
move.o: /usr/include/iso/stddef_iso.h /usr/openwin/include/X11/Xutil.h
move.o: /usr/openwin/include/X11/Xresource.h /usr/include/string.h
move.o: /usr/include/iso/string_iso.h /usr/openwin/include/X11/Core.h
move.o: /usr/openwin/include/X11/Composite.h
move.o: /usr/openwin/include/X11/Constraint.h
move.o: /usr/openwin/include/X11/Object.h /usr/openwin/include/X11/RectObj.h
move.o: /usr/openwin/include/X11/cursorfont.h
move.o: /usr/openwin/include/X11/extensions/shape.h
move.o: /usr/openwin/include/X11/Xfuncs.h /usr/include/strings.h
move.o: /usr/openwin/include/X11/xpm.h icons.h /usr/include/stdlib.h
move.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h screen.h
move.o: list.h menus.h iconmgr.h vdt.h move.h events.h parse.h util.h
move.o: resize.h
LocPixmap.o: twm.h /usr/openwin/include/X11/Intrinsic.h
LocPixmap.o: /usr/openwin/include/X11/Xlib.h /usr/include/sys/types.h
LocPixmap.o: /usr/include/sys/feature_tests.h /usr/include/sys/ccompile.h
LocPixmap.o: /usr/include/sys/isa_defs.h /usr/include/sys/machtypes.h
LocPixmap.o: /usr/include/ia32/sys/machtypes.h /usr/include/sys/int_types.h
LocPixmap.o: /usr/include/sys/select.h /usr/include/sys/time_impl.h
LocPixmap.o: /usr/include/sys/time.h /usr/include/sys/time.h
LocPixmap.o: /usr/openwin/include/X11/X.h
LocPixmap.o: /usr/openwin/include/X11/Xfuncproto.h
LocPixmap.o: /usr/openwin/include/X11/Xosdefs.h /usr/include/stddef.h
LocPixmap.o: /usr/include/iso/stddef_iso.h /usr/openwin/include/X11/Xutil.h
LocPixmap.o: /usr/openwin/include/X11/Xresource.h /usr/include/string.h
LocPixmap.o: /usr/include/iso/string_iso.h /usr/openwin/include/X11/Core.h
LocPixmap.o: /usr/openwin/include/X11/Composite.h
LocPixmap.o: /usr/openwin/include/X11/Constraint.h
LocPixmap.o: /usr/openwin/include/X11/Object.h
LocPixmap.o: /usr/openwin/include/X11/RectObj.h
LocPixmap.o: /usr/openwin/include/X11/cursorfont.h
LocPixmap.o: /usr/openwin/include/X11/extensions/shape.h
LocPixmap.o: /usr/openwin/include/X11/Xfuncs.h /usr/include/strings.h
LocPixmap.o: /usr/openwin/include/X11/xpm.h icons.h /usr/include/stdlib.h
LocPixmap.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h
LocPixmap.o: screen.h list.h menus.h iconmgr.h /usr/include/stdio.h
LocPixmap.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
LocPixmap.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
LocPixmap.o: /usr/include/iso/stdio_c99.h
LocPixmap.o: /usr/openwin/include/X11/Xmu/CvtCache.h
LocPixmap.o: /usr/openwin/include/X11/Xmu/DisplayQue.h
LocPixmap.o: /usr/openwin/include/X11/Xmu/CloseHook.h
LocPixmap.o: /usr/openwin/include/X11/Xmu/Drawing.h /usr/include/limits.h
LocPixmap.o: /usr/include/iso/limits_iso.h /usr/include/sys/param.h
LocPixmap.o: /usr/include/sys/unistd.h
regexp.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
regexp.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
regexp.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
regexp.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
regexp.o: /usr/include/iso/stdio_c99.h regexp.h regmagic.h
